apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: metallb
  namespace: metallb-system
spec:
  chart:
    spec:
      chart: metallb
      version: 0.13.12
      sourceRef:
        kind: HelmRepository
        name: metallb
        namespace: flux-system
  interval: 5m
  install:
    createNamespace: true
  values:
    # Configure your IP address pool
    configInline:
      address-pools:
        - name: default
          protocol: layer2
          addresses:
            - 172.18.0.240-172.18.0.250   # changed to my local cluster subnet

