apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: wordpress
  namespace: wordpress
spec:
  interval: 5m
  install:
    createNamespace: true
  chart:
    spec:
      chart: wordpress
      version: "22.1.9"
      sourceRef:
        kind: HelmRepository
        name: bitnami
        namespace: flux-system
  valuesFrom:
    - kind: Secret
      name: wordpress-values

