apiVersion: ENC[AES256_GCM,data:yvg=,iv:xTK2740aLrpC+qxX4KGw9ymJ1xq9dPbL96I7YWJlIfE=,tag:x+czYKxQi+9D3jY1HgiUeA==,type:str]
kind: ENC[AES256_GCM,data:3APbJTVg,iv:34zeapnLkywAc5gUjJqpXFEhDnoVvzWvANcVpOIZkwc=,tag:cQ4FD4KjZMoR5/uKsFhvDA==,type:str]
metadata:
    name: ENC[AES256_GCM,data:XoRVz8nPlUK9H0hwO3E8+Q==,iv:4WE1yRJ5xdMu/8S+5fErfWhFqZBMF+kO/uSj4x3XJDg=,tag:b+Fhg34kH2FMu3mW4xjCYQ==,type:str]
    namespace: ENC[AES256_GCM,data:ue34XqqOIWoC,iv:/80DzC0NR4/lqg532KITvrdpHNmd/vvUQwLdC/f9Ytg=,tag:bbretkp03Nu8i4POcZs3Aw==,type:str]
stringData:
    values.yaml: ENC[AES256_GCM,data:3OzkYeX73k1X0azC+NV00sn5P0yIb/sslqMTcwaKm4Op24JjzwJqE1G24LLg/pF78ED8kNvFH3hJmYuMkxM3N3pOXCit8o2NvVE02irTlzCkZdiRH/FEB10bNKyV4H6jxxGenM2GZln2TS6rF3Oz8It9e00omRf95znHdjinmNhAAL7GGGj6j+yqQTt8BPasgeXpLuCI5QsaxBK0tE3553lQlJXn9eVk7isdYcpLv2B6MMDhgVQic3J+si1VZgj1MlSa0Vldev+nabKH/ojYJ+LRx2nZtTF3+PilOKDoK8DvszoJ/WqaQP6cgscZFnLAu88BNC+GUOhyHS0=,iv:oOzeiLfFGoaGMNjGd+HC8qiYyKsV6bxXHNyLNPptWGI=,tag:T5dAOFPKjMPvLgwMbC1j9w==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age193sltjwcnwwh2m07g8ektnwwjttf979a9es5y5lcnd33azk854espyxwk9
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAyZFVLSDh3QnlQZjBiVnRV
            TkErRDVqSTlhdjlqZitub25UbFJSMXpaSkdFCkYzQnBPbjZDNWJmdU50TjJBNk9h
            UHg2UU94TGZTVHlGcmwyQ2NvYjNqVHMKLS0tIG1SdmhDM0k0OExOT2JPMTlqeCtu
            dUpoWFNSOTFOcEgyVys1QjVnemcvZUUKpp2wbpaIbtUvNoV4RwZsnNxcPheSUevf
            oDqn70SaqkHDyohEEaic0Z5ADTsD1QWcuxrJV378JDqg2+NHg5gcCg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-09-14T08:05:10Z"
    mac: ENC[AES256_GCM,data:NIsrTMXCsSIZXjU23fvELRkmr6ygAd54Yba4QaysLX5RUV62nkg+82XYRgyeSxM+JpsOfJMhyzIhBgELqXH0Xn5sijO6xb1PWE3iGbi1e6Kvoded/Jsj6BW+qiz5Vnq1jHOAsqjehOya4dZ4nfHKxOAVjLgC0DWee4GDfP4CrO4=,iv:aSuBizUfSG23fJG15/xV/uCM09eOkW2k1aYNsdHWpng=,tag:MgXgUuykhjGVwt+U0MVHZw==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.8.1
